### ISSUE TITLE
Error on example methods

### ISSUE THREAD

**Issue by RomainBrault** [msangnier/qreg#2]
I'm getting an error related to scikit-learn when I run the python file example/methods.py

```
Learn QRegressor
Learn QRegMTL (with location)
Traceback (most recent call last):
  File "examples/methods.py", line 44, in <module>
    mtl.fit(x_train, y_train)
  File "/home/rbrault/anaconda3/lib/python3.6/site-packages/qreg/qreg.py", line 951, in fit
    self.lsr.fit(X_map, y)
  File "/home/rbrault/anaconda3/lib/python3.6/site-packages/sklearn/daal4sklearn/linear.py", line 97, in fit
    daal_fit(self, X, y)
  File "/home/rbrault/anaconda3/lib/python3.6/site-packages/sklearn/daal4sklearn/linear.py", line 35, in daal_fit
    self.trainingResult_ = algorithm.compute()
  File "/home/rbrault/anaconda3/lib/python3.6/site-packages/daal/algorithms/linear_regression/training.py", line 512, in compute
    return _training15.Batch_Float64NormEqDense_compute(self)
SystemError: Failed to solve the system of normal equations
```

My config:

>           conda version : 4.5.2
>     conda-build version : 3.10.1
>          python version : 3.6.3.final.0
> 

Other examples worked fine.

**Comment by RomainBrault** [comment]
OK, indeed this was due to Intel's implementation of scikit-learn, using their DAAL library. Setting Creg=1e12 line 40 solved the problem.
